Add the Saver entity
ozoncp/ocp-presentation-api pull request #13
Opened 2021-06-06 18:06 UTC by arttet

2021-06-06 18:56 UTC, xmikasax requested changes

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/presentation/flusher_test.go
> +		It("", func() {
Пустой It, нужно описание

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/presentation/flusher_test.go
> +		ctx = context.Background()
Нет тестов с экспайром контекста

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/presentation/flusher_test.go
>  		It("", func() {
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/presentation/flusher_test.go
>  		It("", func() {
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/presentation/flusher_test.go
> +			Expect(err).Should(BeEquivalentTo(flusher.ErrInvalidArgument))
gomega / MatchError

https://blog.golang.org/go1.13-errors

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/presentation/flusher_test.go
> +			Expect(err).Should(BeEquivalentTo(errUnsupportedOperation))
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/presentation/flusher_test.go
> +			Expect(err).Should(BeEquivalentTo(errUnsupportedOperation))
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/slide/flusher_test.go
> +		ctx = context.Background()
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/presentation/flusher_test.go
>  		It("", func() {
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/slide/flusher_test.go
> +		It("", func() {
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/slide/flusher_test.go
> +			Expect(err).Should(BeEquivalentTo(flusher.ErrInvalidArgument))
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/slide/flusher_test.go
>  		It("", func() {
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/slide/flusher_test.go
>  		It("", func() {
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/slide/flusher_test.go
> +			Expect(err).Should(BeEquivalentTo(errUnsupportedOperation))
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/slide/flusher_test.go
>  		It("", func() {
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/flusher/slide/flusher_test.go
> +			Expect(err).Should(BeEquivalentTo(errUnsupportedOperation))
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/saver/presentation/saver.go
> +	s.presentation <- presentation
Если передаешь контекст, но здесь должен быть select

2021-06-06 18:56 UTC, xmikasax commented on internal/saver/presentation/saver.go
> +	<-s.done
Я бы не использовал внешний контекст для завершения цикла в сочетании с функцией Close. Close должна завершать цикл сама по себе, а контекст нести дополнительный вариант остановки

2021-06-06 18:56 UTC, xmikasax commented on internal/saver/presentation/saver_test.go
> +		It("", func() {
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/saver/presentation/saver_test.go
> +		It("", func() {
Аналогично

2021-06-06 18:56 UTC, xmikasax commented on internal/time/alarm.go
> +package time
Я бы не стал называть пакет time, чтобы не пересекаться с std

2021-06-06 18:56 UTC, xmikasax commented on internal/time/alarm.go
> +		ctx:     ctx,
Аналогично про контекст

https://dave.cheney.net/2017/08/20/context-isnt-for-cancellation

2021-06-06 18:56 UTC, xmikasax commented on internal/time/alarm.go
> +				a.alarms <- struct{}{}
А если никто не слушает alarms? Я бы добавил select с default

2021-06-07 14:58 UTC, arttet commented on internal/saver/presentation/saver_test.go
> +		It("", func() {
Done

2021-06-07 14:58 UTC, arttet commented on internal/saver/presentation/saver_test.go
> +		It("", func() {
Done

2021-06-07 16:45 UTC, arttet commented on internal/flusher/presentation/flusher_test.go
> +		ctx = context.Background()
Предлагаю добавить их позже.

2021-06-07 16:45 UTC, arttet commented on internal/time/alarm.go
> +		ctx:     ctx,
Предлагаю добавить их позже.

2021-06-07 16:49 UTC, arttet commented on internal/flusher/slide/flusher_test.go
> +		ctx = context.Background()
Предлагаю добавить их позже.

2021-06-07 17:00 UTC, arttet commented on internal/flusher/slide/flusher_test.go
> +		ctx = context.Background()
https://github.com/ozoncp/ocp-presentation-api/issues/14

2021-06-07 17:01 UTC, arttet commented on internal/flusher/presentation/flusher_test.go
> +		ctx = context.Background()
https://github.com/ozoncp/ocp-presentation-api/issues/14

2021-06-07 17:11 UTC, arttet commented on internal/saver/presentation/saver.go
> +	<-s.done
https://github.com/ozoncp/ocp-presentation-api/issues/15

2021-06-07 17:12 UTC, arttet commented on internal/saver/presentation/saver.go
> +	s.presentation <- presentation
Done

2021-06-07 17:12 UTC, arttet commented on internal/time/alarm.go
> +		ctx:     ctx,
https://github.com/ozoncp/ocp-presentation-api/issues/14

2021-06-07 18:19 UTC, rusdevops commented on internal/util/alarm.go
> +				a.done <- struct{}{}
когда нужно закрыть канал `a.done` ?

2021-06-07 18:19 UTC, rusdevops commented on internal/util/alarm.go
> +	alarms := make(chan struct{})
канал должен быть не буферизованный или буферизованный ?

2021-06-07 18:19 UTC, rusdevops commented on internal/saver/presentation/saver.go
> +			time.Sleep(50 * time.Millisecond)
предложу в константы вынести

2021-06-07 22:12 UTC, Tonsofattraction requested changes

2021-06-07 22:12 UTC, Tonsofattraction commented on .vscode/tasks.json
> +        {
Локальные файлы надо добавить в gitignore и убедиться, что они исчезли из remote репозитория

2021-06-08 06:24 UTC, arttet commented on .vscode/tasks.json
> +        {
Я считаю, что это нелокальный файл. Он помогает автоматизировать некоторые задачи (команды).
Думаю, его следует хранить в репозитории, чтобы все имели возможность им воспользоваться.
P.S. https://code.visualstudio.com/docs/editor/tasks

2021-06-08 06:55 UTC, arttet commented on internal/util/alarm.go
> +				a.done <- struct{}{}
Всегда

2021-06-08 06:57 UTC, arttet commented on internal/util/alarm.go
> +	alarms := make(chan struct{})
Сейчас он небуферизованный. Нужно ли его делать буферизованным?

2021-06-08 09:03 UTC, rusdevops commented on internal/util/alarm.go
> +				a.done <- struct{}{}
предложу вызвать `close` без `defer`

2021-06-08 09:08 UTC, rusdevops approved these changes

2021-06-08 09:36 UTC, arttet commented on internal/util/alarm.go
> +				a.done <- struct{}{}
Ок, https://github.com/ozoncp/ocp-presentation-api/issues/16

2021-06-08 09:37 UTC, merged